name: Build ROM

on:
  push:
    branches: [ feature/trainer-overhaul, feature/max-dvs ]
  workflow_dispatch:

env:
  rgbds_version: v1.0.1

jobs:
  build-rom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Checkout rgbds
        uses: actions/checkout@v7
        with:
          path: rgbds
          ref: ${{ env.rgbds_version }}
          repository: gbdev/rgbds

      - name: Install rgbds
        working-directory: rgbds
        run: |
          sudo apt-get update
          sudo apt-get install -yq bison libpng-dev pkg-config
          sudo make -j$(nproc) install

      - name: Remove rgbds
        run: |
          rm -rf rgbds

      - name: Make
        run: |
          make -j$(nproc)

      - name: Upload ROM
        uses: actions/upload-artifact@v4
        with:
          name: pokecrystal-${{ github.ref_name }}-${{ github.sha }}
          path: |
            pokecrystal.gbc
            pokecrystal.sym
            pokecrystal.map
          if-no-files-found: error
